### ISSUE TITLE
Decimal numbers in lobby spawn occured during the parsing

### ISSUE THREAD

**Issue by AndreaCorda01** [Wietje/SkyWars#4]
When you use a command /sw setlobby     in the config write the coord of the lobby in float numbers.
But during the parser, it doesn't accept this float number and give this error.

2013-09-13 23:59:43 [SEVERE] Error occurred while enabling SkyWars v1.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError
        at vc.pvp.skywars.SkyWars.onEnable(SkyWars.java:106)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.loadPlugin(CraftServer.java:286)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.enablePlugins(CraftServer.java:268)
        at net.minecraft.server.v1_6_R2.MinecraftServer.l(MinecraftServer.java:319)
        at net.minecraft.server.v1_6_R2.MinecraftServer.f(MinecraftServer.java:296)
        at net.minecraft.server.v1_6_R2.MinecraftServer.a(MinecraftServer.java:256)
        at net.minecraft.server.v1_6_R2.DedicatedServer.init(DedicatedServer.java:164)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:397)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NumberFormatException: For input string: "232,36"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1241)

I've fixed changing the float number in real number.
Could you fix in the plugin?

**Comment by Wietje** [comment]
The coordinates get parsed as a double on load, which is also a floating number and will get parsed just fine. This is most likely an issue with your OS' locale settings as your floating point values are getting written down with a comma instead of a dot.
